### ISSUE TITLE
Is fedmsg still around?

### ISSUE THREAD

**Issue by pypingou** [etalab/udata#207]
I seem to remember data.gouv.fr used to use fedmsg but I don't seem to be able to find anything about it nowadays. Is fedmsg still around in data.gouv.fr?

Thanks!

**Comment by noirbizarre** [comment]
Hi!

No fedmsg is not used anymore on data.gouv.fr. It's not necesary anymore in the new architecture. Celery + Redis do the job.

**Comment by pypingou** [comment]
On Sat, Oct 17, 2015 at 04:03:56AM -0700, Axel Haustant wrote:
>    Hi!
> 
>    No fedmsg is not used anymore on data.gouv.fr. It's not necesary anymore
>    in the new architecture. Celery + Redis do the job.

Hi,

Thanks for the info, that's a pity I was quite happy about seeing data.gouv.fr
live via fedmsg :(
