### ISSUE TITLE
Provide a way to embed datasets cards within external websites

### ISSUE THREAD

**Issue by davidbgk** [etalab/udata#268]
As a user, I want to embed a dataset on my own website in order to share data links with my visitors.

## Example implementation

To be included by the user on his own website:

```js
<script>window.dgfr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.dgfr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://www.data.gouv.fr/static/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);
 
  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };
 
  return t;
}(document, "script", "dgfr-wjs"));</script>
```

And then wherever he wants to display the card:

```html
<div data-dgfr-dataset-id="53699e2aa3a729239d205dea"></div>
```

On our side, we have to develop the `widgets.js` script and the API returning the [oEmbed](http://oembed.com/) object to generate the appropriated card.

**Comment by davidbgk** [comment]
Example by @simongeorges:

* Following the same pattern: http://cartes-elections.makina-corpus.net/
* Source of the loader: https://github.com/makinacorpus/iframe-loader/blob/master/src/scripts/modules/main-app.js

**Comment by davidbgk** [comment]
![capture d ecran 2015-11-24 a 22 18 17](https://cloud.githubusercontent.com/assets/3556/11380928/57be1a70-92f9-11e5-9f15-92785ba113ef.png)

Incoming!

**Comment by noirbizarre** [comment]
Great ! :)

I'm really curious about the implementation !
